### ISSUE TITLE
fix: benefits link not working

### ISSUE THREAD

**Issue by borjandev** [shorebirdtech/website#131]
**Description**

**Steps To Reproduce**

1. Go to https://shorebird.dev/jobs/
2. Scroll down to 'Compensation'
3. Click on 'benefits' hyperlink
4. See error : 404 - page not found

**Expected Behavior**

Expected to be taken to a 'benefits' page.

**Screenshots**

<img width="586" alt="Screenshot 2024-07-13 at 00 51 24" src="https://github.com/user-attachments/assets/f6aefb1c-df2a-434f-a9e2-e6e9194f9d06">

**Additional Context**

Likely caused by a location change of the benefits.md file in the https://github.com/shorebirdtech/handbook repository

**Comment by eseidel** [comment]
Thanks!  https://handbook.shorebird.dev/benefits/ is the new link
