### ISSUE TITLE
feat: Would like an overages calculator

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/website#212]
Just a tool that I can use during demos when someone asks "how much does it cost to send a patch to 200k people".  It can then do the divide of 200,000 / 2500 = $80.  Right now I pull up google to do that, would be nice to do it on shorebird.dev/pricing so they could do it themselves.

Maybe just a slider similar to the existing "Which plan should I have" one, except all it shows is `$NUMBER / 2500 = $COST`

**Comment by felangel** [comment]
@eseidel can we close this now?

**Comment by eseidel** [comment]
Discussed on Discord.  No, this is to add a (simple) calculator so when a customer asks me in a sales call "how much does it cost to update 1M devices" I can show them how to type 1M on our pricing page and get that answer.
