### ISSUE TITLE
Create shorebird.dev/contact

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/website#3]

**Comment by eseidel** [comment]
I think we end up with a dedicated page which tells you about our discord as well as email. 🤷   But this can also be a later problem. :). The point is to get away from having cryptic discord urls everywhere.  (Which could also be solved by having a discord.shorbird.dev redirect.

**Comment by eseidel** [comment]
I created this over the weekend because we had a url to it:
https://shorebird.dev/contact/
